import bw1 from './bw1.jpeg';
import bw2 from './bw2.jpeg';
import bw3 from './bw3.jpeg';
import bw4 from './bw4.jpeg';
import cc1 from './cc1.jpeg';
import cc2 from './cc2.jpeg';
import cc3 from './cc3.jpeg';
import cc4 from './cc4.jpeg';
import cs1 from './cs1.png';
import cs2 from './cs2.png';
import cs3 from './cs3.png';
import cs4 from './cs4.png';
import cs5 from './cs5.png';
import InstagramIcon from './instagram.svg';
import YoutubeIcon from './youtube.svg';
import GmailIcon from './gmail.svg';
import TelegramIcon from './telegram.svg';
import LinkedInIcon from './linkedin.svg';
import logo from './logo.jpg'
import mlw from './images/machine-learning-workshop.jpeg';
import fw from './images/frontend-workshop.jpg';
import bw from './images/backend-workshop.jpeg';
import maw from './images/mobile-app-workshop.jpg';
import fe1 from './fe1.png';
import fe2 from './fe2.png'
import be1 from './be1.webp';
import be2 from './be2.png'
import be3 from './be3.png'
import ml1 from './ml1.png';
import ma1 from './ma1.png'
export { bw1, bw2, bw3, bw4 , cc1, cc2, cc3, cc4, cs1, cs2, cs3, cs4 ,cs5, InstagramIcon, YoutubeIcon, GmailIcon, TelegramIcon, LinkedInIcon ,logo,mlw,fw,bw,maw,fe1,fe2,be1,be2,be3,ml1,ma1};