import bw1 from './bw1.jpeg';
import bw2 from './bw2.jpeg';
import bw3 from './bw3.jpeg';
import bw4 from './bw4.jpeg';
import cc1 from './cc1.jpeg';
import cc2 from './cc2.jpeg';
import cc3 from './cc3.jpeg';
import cc4 from './cc4.jpeg';
import cs1 from './cs1.png';
import cs2 from './cs2.png';
import cs3 from './cs3.png';
import cs4 from './cs4.png';
import cs5 from './cs5.png';
import InstagramIcon from './instagram.svg';
import YoutubeIcon from './youtube.svg';
import GmailIcon from './gmail.svg';
import TelegramIcon from './telegram.svg';
import LinkedInIcon from './linkedin.svg';
import logo from './logo.jpg'
import mlw from './images/machine-learning-workshop.jpeg';
import fw from './images/frontend-workshop.jpg';
import bw from './images/backend-workshop.jpeg';
import maw from './images/mobile-app-workshop.jpg';
import fe1 from './fe1.png';
import fe2 from './fe2.png'
import be1 from './be1.webp';
import be2 from './be2.png'
import be3 from './be3.png'
import ml1 from './ml1.png';
import ma1 from './ma1.png'
import ed1 from './ed1.jpg';
import ed2 from './ed2.jpg'
import ed3 from './ed3.jpg'
import ed4 from './ed4.jpg'
import ai1 from './ai1.jpg';
import ai2 from './ai2.jpg';
import ai3 from './ai3.jpg';
import ai4 from './ai4.jpg';
import hx1 from './hx1.jpg';
import hx2 from './hx2.jpg';
import hx3 from './hx3.jpg';
import hx4 from './hx4.jpg';
import sih1 from './sih1.jpg';
import sih2 from './sih2.jpg';

export {sih1,sih2,hx1,hx2,hx3,hx4, ai1,ai2,ai3,ai4, bw1, bw2, bw3, bw4 , cc1, cc2, cc3, cc4, cs1, cs2, cs3, cs4 ,cs5, InstagramIcon, YoutubeIcon, GmailIcon, TelegramIcon, LinkedInIcon ,logo,mlw,fw,bw,maw,fe1,fe2,be1,be2,be3,ml1,ma1,ed1,ed2,ed3,ed4};